# Generated by Django 2.2 on 2020-06-14 15:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='mobile_no',
            field=models.PositiveIntegerField(blank=True, default=1, validators=[django.core.validators.MaxValueValidator(9999999999)]),
            preserve_default=False,
        ),
    ]
