# Generated by Django 2.2 on 2020-06-14 16:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0004_auto_20200614_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='clinic_contact_no',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
