# Generated by Django 2.2 on 2020-06-16 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0005_auto_20200614_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='id',
        ),
        migrations.AddField(
            model_name='provider',
            name='profile_name',
            field=models.CharField(default=1, max_length=50, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
